comment: off
coverage:
  status:
    project:
      default:
        target: auto  # this is default
        if_not_found: success
    patch:
      default:
        target: auto  # this is default
        if_not_found: success